spring:
  application:
    name: front_service
server:
  port: 12211
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


